name: Backend CI/CD

on:
  push: 
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch:

env:
  IMAGE_NAME: sally2020s/yg-be
  CONTAINER_NAME: yg-backend

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image with JAR
        run: docker build -t $IMAGE_NAkdME .

      - name: Save Docker image as tar file
        run: docker save $IMAGE_NAME > app.tar

      - name: Upload image artifact to pass to CD
        uses: actions/upload-artifact@v4
        with:
          name: backend-image
          path: app.tar

  cd:
    name: CD
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-image

      - name: Copy Docker image to GCP VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          source: "app.tar"
          target: "~/backend"